# Generated by Django 4.2 on 2024-06-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0002_alter_regions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sities', to='regions.regions')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
