# Generated by Django 4.2 on 2024-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sities',
            name='region',
            field=models.CharField(max_length=32),
        ),
    ]
