# Generated by Django 4.2 on 2024-06-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ('code',)},
        ),
    ]
