# Generated by Django 4.2 on 2024-06-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('inn', models.PositiveIntegerField()),
                ('kpp', models.PositiveIntegerField()),
                ('decent', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='cities.cities')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='regions.regions')),
            ],
        ),
    ]
